### ISSUE TITLE
Exception thrown in get_insight()

### ISSUE THREAD

**Issue by mschwartz** [natekspencer/pylitterbot#108]
This is not an always thing.  Some calls succeed.  This is an occasional thing.  

![2023-01-18 at 3 52 PM](https://user-images.githubusercontent.com/329637/213322278-4005b8d8-db77-47db-a3be-d9796ef64ec9.png)

The insight value is kind of ugly, IMO.  Lots of decimal places in the number!

![2023-01-18 at 3 52 PM](https://user-images.githubusercontent.com/329637/213322553-95d7313c-ffff-412a-a25d-941cd2d42626.png)

It might be good if we can add a get_insight_object() call that has the values as an object and I can format and print that as I want?

**Comment by natekspencer** [comment]
> This is not an always thing. Some calls succeed. This is an occasional thing.

I've noticed this a couple of times on just running a demo script. But because I don't use it for the HA integration and nobody else has brought it up, it's been a very low priority

> It might be good if we can add a get_insight_object() call that has the values as an object and I can format and print that as I want?

`get_insight` already returns an insight object that has the necessary data points that can be formatted however you desire. That's just the default `__str__` representation.

**Comment by mschwartz** [comment]
I haven’t written a lot of python.  More of a JavaScript guy.

a lot of objects that I try to json.dumps() gives me a “not iterable” exception.  There has to be a way that I don’t know to do this.  I’m crafting my own object with key/values from the objects returned by the apis.

But now that I know this is an object, I can deal with it.

thanks!

**Comment by mschwartz** [comment]
Ok, this is now broken for good, it seems.  Since 3/3/2023.  Very call

**Comment by mschwartz** [comment]
Apparently you can't call with days=365 as the argument or the inner HTTP request fails.  Maybe this should be caught in pylitterbot and made to use 30 if > 30, or throw an error saying invalid days.

**Comment by natekspencer** [comment]
So it is working? Just not for large timespans?

**Comment by mschwartz** [comment]
It was working for days=365, then failed once in a while, then it stopped working altogether.  I use this in a long running program.  I first noticed the problem when I opened this ticket.  I changed the days to 365 after looking at the repo, but that was maybe a week ago.  The days=365 stopped working on 3/3.

I'm presenting a graph of pet weights, so I was hoping to get as long term data as possible.

Thanks for the reply and the project!

**Comment by mschwartz** [comment]
FYI

![2023-03-06 at 12 48 PM](https://user-images.githubusercontent.com/329637/223227322-ad2e0929-e597-47f7-becc-c3f25f746a54.png)

**Comment by jacobmcclure** [comment]
I'm not sure if the endpoint is broken or if I'm just doing something very incorrectly, but I'm unable to reach the api for some reason I am getting the following each time I attempt to authenticate:

`Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/aiohttp/connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/base_events.py", line 1092, in create_connection
    transport, protocol = await self._create_connection_transport(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/base_events.py", line 1122, in _create_connection_transport
    await waiter
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/sslproto.py", line 534, in data_received
    ssldata, appdata = self._sslpipe.feed_ssldata(data)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/sslproto.py", line 188, in feed_ssldata
    self._sslobj.do_handshake()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/ssl.py", line 975, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pylitterbot/account.py", line 80, in connect
    await self.session.login(username=username, password=password)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pylitterbot/session.py", line 171, in login
    token = await self.post(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pylitterbot/session.py", line 46, in post
    return await self.request("POST", path, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pylitterbot/session.py", line 212, in request
    return await super().request(method, url, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pylitterbot/session.py", line 80, in request
    async with self.websession.request(method, url, **kwargs) as resp:
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/aiohttp/client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/aiohttp/client.py", line 536, in _request
    conn = await self._connector.connect(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/aiohttp/connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/aiohttp/connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/aiohttp/connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/aiohttp/connector.py", line 1175, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/aiohttp/connector.py", line 982, in _wrap_create_connection
    raise ClientConnectorCertificateError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorCertificateError: Cannot connect to host 42nk7qrhdg.execute-api.us-east-1.amazonaws.com:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)')]

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/jacob.mcclure/Desktop/lr3.py", line 28, in <module>
    asyncio.run(main())
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/Users/jacob.mcclure/Desktop/lr3.py", line 16, in main
    await account.connect(username=username, password=password, load_robots=True)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pylitterbot/account.py", line 96, in connect
    raise LitterRobotException("Unable to reach the Litter-Robot api.") from ex
pylitterbot.exceptions.LitterRobotException: Unable to reach the Litter-Robot api.`

**Any idea what could be causing this? SOS**

**Comment by natekspencer** [comment]
@jacobmcclure this is unrelated to the issue title, please create a separate issue

**Comment by mschwartz** [comment]
Thanks!  Looks like it will throw an Exception when NoneType.  In dev branch.

Looking forward to it!
