### ISSUE TITLE
Can't import account from pylitterbot

### ISSUE THREAD

**Issue by MCHamlet** [natekspencer/pylitterbot#132]
Traceback (most recent call last):
  File "litterbot.py", line 3, in <module>
    from pylitterbot import Account
  File "/usr/local/lib/python3.6/site-packages/pylitterbot/__init__.py", line 3, in <module>
    from .account import Account
  File "/usr/local/lib/python3.6/site-packages/pylitterbot/account.py", line 9, in <module>
    from .robot import LITTER_ROBOT_ID, Robot
  File "/usr/local/lib/python3.6/site-packages/pylitterbot/robot.py", line 376
    sleep_time := int(today_at_time(sleep_time).timestamp())
               ^
SyntaxError: invalid syntax

**Comment by natekspencer** [comment]
Looks like you're using an unsupported python version.

**Comment by MCHamlet** [comment]
Oh sorry my mistake. Whats the most recent supported version?

**Comment by natekspencer** [comment]
3.7.2 I think works. But I only test again 3.8+
